name: Bug Report
description: Report a bug to help us improve
labels: ["bug", "needs triage"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please confirm the following:
      options:
        - label: 1
          required: false
        - label: 2
          required: false
        - label: 3
          required: false
        - label: 4
          required: true
