name: Bug Report1
description: Report a bug to echarts-config1
title: "[Bug] "
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
      - label: I have searched the existing issues2
